### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by fixer112** [lunahq/flutter-crisp#35]
Hello am getting Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at im.crisp.client.internal.c.b.c(:23) from crashlytic firebase. am using crisp 0.3.1.

Full log:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at im.crisp.client.internal.c.b.c(:23)
       at im.crisp.client.internal.f.b.a(:293)
       at im.crisp.client.internal.f.b.a(:1)
       at io.socket.emitter.Emitter.emit(Emitter.java:26)
       at io.socket.client.Socket.onevent(Socket.java:83)
       at io.socket.client.Socket.onpacket(Socket.java:35)
       at io.socket.client.Socket.access$100(Socket.java)
       at io.socket.client.Socket$2$2.call(Socket.java:9)
       at io.socket.emitter.Emitter.emit(Emitter.java:26)
       at io.socket.client.Manager.ondecoded(Manager.java:8)
       at io.socket.client.Manager.access$1200(Manager.java)
       at io.socket.client.Manager$5.call(Manager.java:2)
       at io.socket.parser.IOParser$Decoder.add(IOParser.java:35)
       at io.socket.client.Manager$2.call(Manager.java:15)
       at io.socket.emitter.Emitter.emit(Emitter.java:26)
       at io.socket.engineio.client.Socket.onPacket(Socket.java:194)
       at io.socket.engineio.client.Socket.access$1000(Socket.java)
       at io.socket.engineio.client.Socket$5.call(Socket.java:12)
       at io.socket.emitter.Emitter.emit(Emitter.java:26)
       at io.socket.engineio.client.Transport.onPacket(Transport.java:8)
       at io.socket.engineio.client.Transport.onData(Transport.java:4)
       at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java)
       at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:6)
       at io.socket.thread.EventThread$2.run(EventThread.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Pls how do i fix this?

**Comment by mr-mamali** [comment]
same issue when a user wants to send attachment file after selecting media or file this error is invoked and app crashed
